import type { VersionEntry } from './types';

export const REPO = 'https://github.com/shakzmaos-jung/getkkul';
export const prUrl = (n: number) => `${REPO}/pull/${n}`;

/**
 * getkkul 서비스 릴리스 이력(최신순). 단일소스는 apps/web/package.json + CHANGELOG.md 지만,
 * 여기엔 3단계 설명(개발자/비개발자/사용자영향)까지 저술해 어드민에서 조회한다.
 * date 는 실제 머지날짜(KST). 신규 릴리스 시 이 배열 최상단에 엔트리를 추가한다(ADR-0012).
 */
export const VERSION_HISTORY: VersionEntry[] = [
  {
    version: '0.13.0',
    date: '2026-07-17',
    type: 'minor',
    prs: [120],
    summary: '용어 정의 인라인 툴팁 + 어드민 용어사전(수정·이력) + 요약 오타 교정 확대',
    dev: '요약 단일 호출에 terms 추출을 접붙여(추가 LLM 0) content_terms 캐시. 신규 스테이지 defineGlossaryPending 이 미정의 용어만 배치 정의 → 전역 glossary_terms(용어당 1회, 재사용). 읽기는 get_video_glossary(본문×사전 매칭)로 LLM 0. 카드 renderWithTerms + TermTooltip(점선·탭). 설정 term_tooltips 토글. 어드민 용어사전: get_glossary 조회 + edit_glossary_term(원자적 정의수정+source=admin+이력) — 어드민 최초 WRITE. summarize 프롬프트에 일반 오타 교정 확대 + PROMPT_VERSION bump.',
    nonDev: '요약을 읽다가 모르는 용어에 점선이 보이면 눌러서 바로 뜻을 볼 수 있다(예전 AI 질의처럼 기다리지 않고 즉시). 용어 뜻은 한 번만 만들어 재사용하므로 비용도 아낀다. 관리자 화면에는 용어사전을 조회·수정하고 누가 언제 고쳤는지 보는 메뉴가 생겼다. 전사 과정에서 생기던 오타도 요약에서 더 많이 바로잡는다.',
    userImpact: '요약 속 어려운 용어를 탭 한 번으로 즉시 이해할 수 있고(설정에서 끌 수 있음), 요약의 오타가 줄어든다. 기존 영상이 아니라 새로 처리되는 영상부터 적용된다.',
  },
  {
    version: '0.12.1',
    date: '2026-07-17',
    type: 'patch',
    prs: [119],
    summary: '발송 중복·개수불일치 인시던트 수정 + 어드민 발송 이력 메뉴',
    dev: '이중 트리거(GitHub 크론 제거→pg_cron 단독) + send_log(user,slot,day) 원자적 클레임으로 슬롯당 1회 발송 보장. 발송→기록 레이스와 빈 core_text 요약 포함(제목≠본문)도 수정. 어드민 get_send_history 기반 발송 이력 메뉴(필터·검색·마스킹).',
    nonDev: '한 알림 시간에 이메일이 여러 통 가거나, 제목의 개수와 본문 개수가 다르던 문제를 고쳤다. 관리자 화면에는 실제 발송 내역을 조회하는 메뉴를 추가했다.',
    userImpact: '이제 한 발송 시간대(07:30 등)에 이메일이 정확히 한 통만 오고, 제목에 표시된 개수와 본문 콘텐츠 개수가 일치한다.',
  },
  {
    version: '0.12.0',
    date: '2026-07-15',
    type: 'minor',
    prs: [117],
    summary: '다이제스트 싫어요 사유 모달 + 어드민 좋아요/싫어요 이벤트 이력',
    dev: '요약 카드 👎 클릭 시 사유 입력 모달(≤200자). 반응을 content_feedback(현재상태)와 feedback_events(추가전용 로그)에 이중 기록. 어드민에 get_feedback_events RPC 기반 "피드백" 메뉴(필터·검색·이메일 마스킹·KST).',
    nonDev: '사용자가 요약을 "별로"라고 표시할 때 왜 별로였는지 적어 보낼 수 있게 하고, 운영자는 관리자 화면에서 좋아요/싫어요 기록을 모아 본다.',
    userImpact: '요약이 아쉬울 때 이유를 남길 수 있고, 그 피드백이 품질 개선에 쓰인다.',
  },
  {
    version: '0.11.3',
    date: '2026-07-15',
    type: 'patch',
    prs: [116],
    summary: '홈 대시보드 다듬기 — 라벨 축약 · 카드 높이 정렬',
    dev: "'원본 영상 시간 누계'→'원본 영상 시간' 축약, 두 통계 카드 높이를 flex stretch 로 일치(퍼센트 높이 폴백 문제 해소).",
    nonDev: '홈 상단 통계 카드의 글자를 줄이고 두 카드 크기를 나란히 맞췄다.',
    userImpact: '홈 화면 통계가 더 정돈되어 보인다.',
  },
  {
    version: '0.11.2',
    date: '2026-07-15',
    type: 'patch',
    prs: [115],
    summary: "'원본 영상 시간'을 '총 누적 다이제스트' 카드 안으로 통합(2카드)",
    dev: '별도 원본시간 카드를 총 누적 다이제스트 카드의 하위 지표로 이동 → 대시보드 3→2 카드.',
    nonDev: '홈 통계를 카드 2개로 간결화했다.',
    userImpact: '홈 상단이 덜 복잡해진다.',
  },
  {
    version: '0.11.1',
    date: '2026-07-15',
    type: 'patch',
    prs: [114],
    summary: '홈 대시보드를 누적 가치 중심 3카드로 재구성',
    dev: "'이번달 다이제스트'·'구독 채널' 카드 제거, 총 누적 다이제스트→원본 영상 시간→압축 영상 시간(절약·압축률 보조) 순 재편.",
    nonDev: '홈 통계를 "그동안 얼마나 아꼈나" 중심으로 다시 배치했다.',
    userImpact: '서비스가 절약해준 시간이 더 잘 드러난다.',
  },
  {
    version: '0.11.0',
    date: '2026-07-15',
    type: 'minor',
    prs: [113],
    summary: '홈 상단 통계를 1×3 대시보드 그리드로 강조',
    dev: '인라인 3칩을 강조 숫자+보조지표의 대시보드 카드로 승격(get_month_value_stats 재사용, 스키마 무변경).',
    nonDev: '홈 상단 숫자들을 큼직한 대시보드 형태로 바꿨다.',
    userImpact: '누적 다이제스트·이번달·구독 채널 수가 한눈에 들어온다.',
  },
  {
    version: '0.10.2',
    date: '2026-07-15',
    type: 'patch',
    prs: [112],
    summary: "개발자 정보의 '리멤버 프로필' 링크 삭제",
    dev: 'Developer Info 연락처에서 리멤버 링크·미사용 아이콘/URL 제거(이메일·GitHub 유지).',
    nonDev: '개발자 소개 화면에서 불필요한 외부 링크를 뺐다.',
    userImpact: '개발자 정보가 깔끔해진다(기능 영향 없음).',
  },
  {
    version: '0.10.1',
    date: '2026-07-15',
    type: 'patch',
    prs: [111],
    summary: '구독 채널 검색 UX 개선 — 등록 후 자동 닫힘 · 피드백 · 닫기 버튼',
    dev: '채널 등록 성공 시 완료 안내+결과목록 자동 닫힘, 이미 구독 시 안내(addSubscriptionState.already), 결과목록 닫기 버튼 추가.',
    nonDev: '채널을 검색해 추가할 때 결과창이 알아서 닫히고, 이미 있는 채널인지 알려준다.',
    userImpact: '채널 추가가 더 매끄럽고 헷갈리지 않는다.',
  },
  {
    version: '0.10.0',
    date: '2026-07-15',
    type: 'minor',
    prs: [110],
    summary: '멤버십 채널 한도 상시 시행 + 다운그레이드 자동정지 · 수동 복원',
    dev: 'membership_enforce_all_limits() 를 주기 잡이 호출해 한도 초과를 불변식으로 자동정지(최신순). 업그레이드 자동복원 제거→수동 해제. ADR-0015 개정.',
    nonDev: '요금제별 채널 개수 한도를 항상 지키도록 초과분을 자동 일시정지하고, 요금제를 올려도 저절로 되살리지 않고 사용자가 직접 켠다.',
    userImpact: '한도를 넘은 채널은 사유와 함께 자동 정지되며, 상위 플랜에서 직접 해제한다.',
  },
  {
    version: '0.9.1',
    date: '2026-07-14',
    type: 'patch',
    prs: [109],
    summary: "설정 화면의 '테마' 카드 제거",
    dev: '테마 선택을 사이드패널 "화면" 아코디언으로 일원화, 설정의 중복 카드 삭제.',
    nonDev: '화면 테마를 고르는 곳을 사이드 메뉴 한 곳으로 모았다.',
    userImpact: '테마 설정 위치가 단순해진다.',
  },
  {
    version: '0.9.0',
    date: '2026-07-14',
    type: 'minor',
    prs: [108],
    summary: '콘텐츠 3탭을 상세도 스펙트럼(간단히<자세히<최대한)으로 재편',
    dev: 'short/normal/long 을 3탭에 1:1 매핑, 요약 시스템 프롬프트를 3단계 상세도로 재작성(PROMPT_VERSION bump), 탭별 선호/피드백 분리 저장. 스키마·재생성 없음.',
    nonDev: "요약을 '간단히/자세히/최대한' 3단계로 골라 볼 수 있게 정리했다.",
    userImpact: '원하는 만큼의 요약 깊이를 탭으로 선택할 수 있다.',
  },
  {
    version: '0.8.2',
    date: '2026-07-14',
    type: 'patch',
    prs: [107],
    summary: '사이드패널 테마 아코디언에 설명 문구 표시',
    dev: '테마 아코디언 각 항목에 설명 텍스트 표시(설정 화면과 동일), compact 모드는 레이아웃만 담당.',
    nonDev: '테마를 고를 때 각 테마 설명도 함께 보여준다.',
    userImpact: '어떤 테마인지 설명을 보고 고를 수 있다.',
  },
  {
    version: '0.8.1',
    date: '2026-07-14',
    type: 'patch',
    prs: [106],
    summary: '사이드패널 테마 선택을 인라인 아코디언으로',
    dev: "'화면>테마'를 설정 이동 대신 그 자리 아코디언으로 펼쳐 선택(실시간 미리보기), 설정 카드는 두 번째 진입점으로 유지.",
    nonDev: '사이드 메뉴에서 화면을 떠나지 않고 바로 테마를 고르고 미리 볼 수 있다.',
    userImpact: '테마를 즉시 비교하며 고를 수 있다.',
  },
  {
    version: '0.8.0',
    date: '2026-07-14',
    type: 'minor',
    prs: [105],
    summary: '읽기 테마 5종 + 시스템(라이트 · 다크 톤조정 · 페이퍼 · 그레이스케일 · 나이트시프트)',
    dev: '5개 읽기 테마+시스템, 즉시·무깜빡임 적용, localStorage+DB(user_settings.theme) 저장, 색상 CSS 변수 토큰화 + WCAG AA 대비·동기화 테스트. 다크 톤 상향, 라이트 accent AA 교정.',
    nonDev: '읽기 편한 화면 테마를 5가지(+기기 설정 따르기) 제공한다.',
    userImpact: '취향·환경에 맞는 화면 테마를 고를 수 있고 다음에도 기억된다.',
  },
  {
    version: '0.7.6',
    date: '2026-07-14',
    type: 'patch',
    prs: [104],
    summary: '개발자 정보 프로필 사진 추가',
    dev: 'public/profile.png(512²) → Developer Info 아바타가 실제 원형 사진 표시("정" 이니셜 폴백 대체).',
    nonDev: '개발자 소개에 실제 프로필 사진을 넣었다.',
    userImpact: '개발자 정보 화면에 사진이 보인다.',
  },
  {
    version: '0.7.5',
    date: '2026-07-14',
    type: 'patch',
    prs: [103],
    summary: '홈 히어로 하단 통계 3칩 정리',
    dev: '그동안 누적·이번달 누적 영상(신규 period_count, 멤버십 주기 기준)·구독 중인 채널 3칩. get_digest_summary 에 period_count 추가(today/total 불변).',
    nonDev: '홈 상단에 누적·이번달·구독 채널 수를 칩 3개로 보여준다.',
    userImpact: '내 사용 현황 숫자를 홈에서 확인한다.',
  },
  {
    version: '0.7.4',
    date: '2026-07-14',
    type: 'patch',
    prs: [102],
    summary: '발송 선별 조회 실패를 삼키지 않고 throw(오탐 방지)',
    dev: 'candidateVideos 하위쿼리가 에러를 빈 배열로 삼키던 것을 throw 로 전환 → 일시적 읽기 실패가 "새 소식 없음"으로 위장 못 함. 회귀 테스트 추가.',
    nonDev: '시스템 오류를 "새 소식 없음"으로 잘못 알리던 위험을 막았다.',
    userImpact: '새 다이제스트가 있는데 "없음"으로 잘못 안내될 위험이 줄었다.',
  },
  {
    version: '0.7.3',
    date: '2026-07-13',
    type: 'patch',
    prs: [100],
    summary: '발송 정체 모니터링 신호 추가',
    dev: 'pipeline_health_snapshot 에 stuckDeliveryUsers(요약 있으나 26h 내 0건 발송) + health-check 경보. 26h 게이트로 대량 백로그 오탐 방지. 회귀 테스트.',
    nonDev: '발송이 막혀 있는 상황을 운영자가 감지하도록 경보를 달았다.',
    userImpact: '발송 장애를 더 빨리 발견·복구해 누락을 줄인다(간접).',
  },
  {
    version: '0.7.2',
    date: '2026-07-13',
    type: 'patch',
    prs: [99],
    summary: '고볼륨 구독자 미발송 복구(1000행 상한 버그)',
    dev: 'candidateVideos done-영상 조회가 서버 max-rows(1000)에 걸려 >1000 영상 사용자가 오래된 1000개(전부 멤버십 이전)만 받아 0 후보 → 멤버십 하한을 SQL(.gte published_at)로 밀고 .limit 명시. 회귀 테스트.',
    nonDev: '영상이 아주 많은 사용자에게 다이제스트가 안 나가던 버그를 고쳤다.',
    userImpact: '구독·시청이 많은 사용자도 다이제스트를 정상 수신한다.',
  },
  {
    version: '0.7.1',
    date: '2026-07-13',
    type: 'patch',
    prs: [98],
    summary: '보안 하드닝 · 파이프라인 격리 · OTP 남용 방지',
    dev: 'OTP 쿨다운/횟수제한(otp_attempts), open-redirect 방어(safeNextPath), IDOR 명시 필터, requireAdmin 게이트, 로그 위생. 파이프라인 stage 격리(runStage). 다수 테스트.',
    nonDev: '로그인 인증코드 남용 방지, 악성 링크·권한 우회 방어 등 보안을 강화했다.',
    userImpact: '계정·데이터가 더 안전해진다(직접 보이는 변화는 없음).',
  },
  {
    version: '0.7.0',
    date: '2026-07-12',
    type: 'minor',
    prs: [84],
    summary: '파이프라인 자동 점검·리포트(하루 8회 이메일)',
    dev: 'gk_pipeline_check(ADR-0016) 4단계 8회/일 점검→운영자 이메일(✅/⚠️), pipeline_health_snapshot, pg_cron↔GitHub Actions 이중화, 백로그 신호 2026-07-10 이후로 게이트.',
    nonDev: '서비스가 잘 돌아가는지 자동 점검해 운영자에게 하루 여러 번 알린다.',
    userImpact: '장애를 조기 발견해 서비스 안정성이 올라간다(간접).',
  },
  {
    version: '0.6.4',
    date: '2026-07-12',
    type: 'patch',
    prs: [83],
    summary: '크레딧 현황 지표 워딩 간결화',
    dev: '크레딧 지표 문구 → 누적 획득 / 누적 사용 / 현재 잔여.',
    nonDev: '크레딧 화면 문구를 더 명확히 다듬었다.',
    userImpact: '크레딧 현황이 더 이해하기 쉽다.',
  },
  {
    version: '0.6.3',
    date: '2026-07-12',
    type: 'patch',
    prs: [82],
    summary: 'GNB · 배너 톤 · 크레딧 워딩 · 태그라인',
    dev: "하단 GNB '채널'→'구독 채널', 얼리버드 배너 톤(파란 하트), 크레딧 워딩, 태그라인 '구독한 유튜브 콘텐츠의 핵심만'.",
    nonDev: '메뉴 이름·배너·소개 문구를 다듬었다.',
    userImpact: '문구가 더 명확해진다.',
  },
  {
    version: '0.6.2',
    date: '2026-07-12',
    type: 'patch',
    prs: [81],
    summary: '서비스 소개 · 개발자 정보 문안 보강(i18n)',
    dev: '소개 화면(한줄/왜/누구에게/사용법)·개발자 정보(프로필 슬롯+바이오) 확장, 문구 i18n(messages.ko.json about·developer).',
    nonDev: '서비스 소개와 개발자 소개 내용을 풍부하게 했다.',
    userImpact: '서비스가 무엇인지·누가 만들었는지 더 잘 알 수 있다.',
  },
  {
    version: '0.6.1',
    date: '2026-07-12',
    type: 'patch',
    prs: [80],
    summary: '알림카드 2×2 · 라벨 통일 · 툴팁 · 마스킹 수정',
    dev: '알림시각 카드 1×4→2×2, 요약길이 라벨 통일. 길이필터 툴팁 투명배경(포털) 수정, 초대내역 이메일 마스킹, 얼리버드 배너 가시성 수정.',
    nonDev: '알림 설정 카드 배치와 여러 표시 오류를 손봤다.',
    userImpact: '설정 화면이 정돈되고 초대 이메일이 가려진다.',
  },
  {
    version: '0.6.0',
    date: '2026-07-12',
    type: 'minor',
    prs: [79],
    summary: '다이제스트 탭 재구성 · 홈 위계 · 초대/크레딧 정리',
    dev: '탭 요점/핵심/심층→간단히/자세히/인사이트, 홈 가치 히어로 강조, 초대/크레딧 정리·가이드 뱃지, 알림카드 2×2→1×4, 피드백 툴팁, 초대내역 마스킹.',
    nonDev: '요약 탭 이름과 홈 화면 구성을 크게 정리했다.',
    userImpact: '요약 선택과 홈 화면이 더 직관적이다.',
  },
  {
    version: '0.5.1',
    date: '2026-07-12',
    type: 'patch',
    prs: [78],
    summary: '영상 하한 2분 통일 + ⓘ 툴팁 + 피드 회귀 복구',
    dev: '길이필터 ⓘ 탭 툴팁(모바일), 영상 최소 2분(120s) 통일·비소급(created_at grandfather), 2026-07-12 요약 개편발 get_feed_digests 회귀 2건 복구.',
    nonDev: '너무 짧은 영상 기준을 2분으로 통일하고 관련 버그를 고쳤다.',
    userImpact: '2분 미만 영상은 제외되고, 다이제스트 누락 버그가 사라진다.',
  },
  {
    version: '0.5.0',
    date: '2026-07-12',
    type: 'minor',
    prs: [77],
    summary: '홈 가치 히어로 · 크레딧 메뉴 · 다운그레이드 채널 정지',
    dev: '홈 Value Hero(인사말+플랜배지+이번달 압축·절약), 사이드 "크레딧" 메뉴(/credits), 초대/크레딧 분리, 다운그레이드 초과 채널을 사유 정지+업그레이드 자동복원(pause_reason, ADR-0015).',
    nonDev: '홈에 "이번달 아껴준 시간"을 보여주고, 크레딧 메뉴를 분리했다.',
    userImpact: '서비스 가치를 홈에서 체감하고, 크레딧을 따로 관리한다.',
  },
  {
    version: '0.4.0',
    date: '2026-07-12',
    type: 'minor',
    prs: [76],
    summary: '요약 렌더 개선 · 깊이 재정의 · 하이라이트 제거',
    dev: '요점/핵심/심층 불릿 배열(줄바꿈), 깊이 명확화, 라벨 짧게/보통/길게→요점/핵심/심층, 이메일 다이제스트 불릿화, 핵심문장 하이라이트(밑줄) 제거.',
    nonDev: '요약을 항목별 불릿으로 보여주고 라벨을 정리했다.',
    userImpact: '요약이 더 읽기 쉬운 형태가 된다.',
  },
  {
    version: '0.3.0',
    date: '2026-07-12',
    type: 'minor',
    prs: [75],
    summary: '요약 품질 재설계(정보계층) + 👍/👎 피드백 루프',
    dev: '길이 모드를 문장수→정보계층으로 재정의(long=핵심사실+맥락·인사이트+하이라이트), 단조성 가드, 보수적 전사교정. 카드 👍/👎 피드백+운영 지표, prompt_version 관리+회귀 테스트.',
    nonDev: '요약 품질을 정보 계층 기반으로 크게 개선하고 좋아요/싫어요를 도입했다.',
    userImpact: '요약이 더 충실해지고 평가를 남길 수 있다.',
  },
  {
    version: '0.2.0',
    date: '2026-07-11',
    type: 'minor',
    prs: [74],
    summary: '발송 슬롯 21:30 · 친구초대 메뉴 + 버전 관리 체계 도입',
    dev: '21:30 KST 발송 슬롯(이메일/푸시+설정), "친구 초대 & 크레딧"(/referral), 버전 체계 도입(CHANGELOG·git 태그·ADR-0012), pg_cron 정시 디스패치 시각 가드.',
    nonDev: '저녁 9시 반 발송을 추가하고 친구 초대 메뉴를 넣었으며, 버전 관리 체계를 시작했다.',
    userImpact: '밤 발송 시간대가 늘고 친구 초대가 가능해진다.',
  },
  {
    version: '0.1.0',
    date: '2026-07-11',
    type: 'baseline',
    prs: [],
    summary: '초기 베이스라인 — 겟꿀 핵심 기능 전체',
    dev: '유튜브 채널 구독·영상 감지·전사·요약·하루 정시 발송(이메일/웹푸시), 멤버십/크레딧·레퍼럴, PWA, 설정/다이제스트/홈 화면. 버전 체계 이전 전체 누적(≤PR #73).',
    nonDev: '겟꿀의 첫 완성본 — 구독한 유튜브를 대신 요약해 정해진 시간에 보내주는 핵심 기능 전부.',
    userImpact: '서비스의 기본 기능(요약·정시 발송·구독 관리)을 사용할 수 있다.',
  },
];

export const CURRENT_VERSION = VERSION_HISTORY[0].version;
